---
swagger: "2.0"
info:
  description: "An API to create backup and restoration"
  version: "1.0.0"
  title: "TOC API"
  termsOfService: "http://gyk4j.github.io/terms/"
  contact:
    email: "147011991+gyk4j@users.noreply.github.com"
  license:
    name: "Eclipse Public License 2.0 (EPL)"
    url: "https://www.eclipse.org/legal/epl-2.0/"
host: "toc"
basePath: "/v1"
tags:
- name: "backup"
  description: "For creating new backup snapshots and querying backup info"
  externalDocs:
    description: "Find out more about TOC"
    url: "https://github.com/gyk4j/toc"
- name: "restoration"
  description: "For performing backup restoration and querying restoration info and\
    \ status"
  externalDocs:
    description: "Find out more about TOC"
    url: "https://github.com/gyk4j/toc"
- name: "transfer"
  description: "For transferring backup snapshots and querying transfer info and status"
  externalDocs:
    description: "Find out more about TOC"
    url: "https://github.com/gyk4j/toc"
- name: "synchronization"
  description: "For sychronizing backup snapshots latest status"
  externalDocs:
    description: "Find out more about TOC"
    url: "https://github.com/gyk4j/toc"
- name: "quota"
  description: "For checking quota limits"
  externalDocs:
    description: "Find out more about TOC"
    url: "https://github.com/gyk4j/toc"
- name: "log"
  description: "For exporting server logs"
  externalDocs:
    description: "Find out more about TOC"
    url: "https://github.com/gyk4j/toc"
- name: "archive"
  description: "For creating backup data ZIP archives"
  externalDocs:
    description: "Find out more about TOC"
    url: "https://github.com/gyk4j/toc"
schemes:
- "http"
paths:
  /backups:
    get:
      tags:
      - "backup"
      summary: "Query backup info"
      description: "Retrieve information and state of all backups and their snapshots"
      operationId: "getBackup"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Backup info retrieved"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Backup"
        "403":
          description: "Forbidden from querying backup info"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Backup not found"
          schema:
            $ref: "#/definitions/ApiResponse"
        "405":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ApiResponse"
        "500":
          description: "TOC controller error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "503":
          description: "Service unavailable"
          schema:
            $ref: "#/definitions/ApiResponse"
    post:
      tags:
      - "backup"
      summary: "Create a new backup snapshot"
      description: "Create a new backup snapshot"
      operationId: "newBackup"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Backup started"
          schema:
            $ref: "#/definitions/ApiResponse"
        "403":
          description: "Forbidden from creating duplicate/repeat backup"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Main backup server not found"
          schema:
            $ref: "#/definitions/ApiResponse"
        "405":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ApiResponse"
        "500":
          description: "Main TOC controller error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "502":
          description: "Bad gateway. Main backup server error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "503":
          description: "Service unavailable on main TOC controller"
          schema:
            $ref: "#/definitions/ApiResponse"
        "504":
          description: "Gateway timeout. Main backup server did not reply."
          schema:
            $ref: "#/definitions/ApiResponse"
  /backups/{backupId}:
    get:
      tags:
      - "backup"
      summary: "Find backup by ID"
      description: "Query a single backup"
      operationId: "getBackupById"
      produces:
      - "application/json"
      parameters:
      - name: "backupId"
        in: "path"
        description: "ID of backup to return"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "BackupId"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Backup"
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Backup not found"
          schema:
            $ref: "#/definitions/ApiResponse"
  /restorations:
    get:
      tags:
      - "restoration"
      summary: "Query restoration info"
      description: "Retrieve information and state of all restorations, their backup\
        \ and snapshots"
      operationId: "getRestoration"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Restoration info retrieved"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Restoration"
        "403":
          description: "Forbidden from querying restoration info"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Restoration not found"
          schema:
            $ref: "#/definitions/ApiResponse"
        "405":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ApiResponse"
        "500":
          description: "TOC controller error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "503":
          description: "Service unavailable"
          schema:
            $ref: "#/definitions/ApiResponse"
    post:
      tags:
      - "restoration"
      summary: "Start a backup restoration attempt"
      description: "Run backup restoration and return immediately without waiting"
      operationId: "newRestoration"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Backup and associated snapshots for restoration"
        required: true
        schema:
          $ref: "#/definitions/Backup"
        x-exportParamName: "Body"
      responses:
        "200":
          description: "Restoration started"
          schema:
            $ref: "#/definitions/ApiResponse"
        "403":
          description: "Forbidden from creating duplicate/repeat restoration"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Stepup backup server not found"
          schema:
            $ref: "#/definitions/ApiResponse"
        "405":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ApiResponse"
        "500":
          description: "Stepup TOC controller error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "502":
          description: "Bad gateway. Stepup backup server error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "503":
          description: "Service unavailable on stepup TOC controller"
          schema:
            $ref: "#/definitions/ApiResponse"
        "504":
          description: "Gateway timeout. Stepup backup server did not reply."
          schema:
            $ref: "#/definitions/ApiResponse"
  /restorations/{restorationId}:
    get:
      tags:
      - "restoration"
      summary: "Find restoration by ID"
      description: "Query a single restoration"
      operationId: "getRestorationById"
      produces:
      - "application/json"
      parameters:
      - name: "restorationId"
        in: "path"
        description: "ID of restoration to return"
        required: true
        type: "integer"
        format: "int64"
        x-exportParamName: "RestorationId"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Restoration"
        "400":
          description: "Invalid ID supplied"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Restoration not found"
          schema:
            $ref: "#/definitions/ApiResponse"
  /synchronizations:
    post:
      tags:
      - "synchronization"
      summary: "Request backup snapshot synchronization between main and stepup controller"
      description: "Initiates backup snapshot state synchronization due to network\
        \ disconnection"
      operationId: "newSynchronization"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Synchronization started"
          schema:
            $ref: "#/definitions/ApiResponse"
        "403":
          description: "Forbidden from starting synchronization"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "TOC controller not found"
          schema:
            $ref: "#/definitions/ApiResponse"
        "405":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ApiResponse"
        "500":
          description: "TOC controller error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "502":
          description: "Bad gateway. Backup server error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "503":
          description: "Service unavailable on TOC controller"
          schema:
            $ref: "#/definitions/ApiResponse"
        "504":
          description: "Gateway timeout. One or more servers did not reply."
          schema:
            $ref: "#/definitions/ApiResponse"
  /quotas:
    get:
      tags:
      - "quota"
      summary: "Refresh quota info"
      description: "Retrieve all quotas set"
      operationId: "getQuota"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Quotas retrieved"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Quota"
        "403":
          description: "Forbidden from querying quota info"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Quota not found"
          schema:
            $ref: "#/definitions/ApiResponse"
        "405":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ApiResponse"
        "500":
          description: "TOC controller error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "503":
          description: "Service unavailable"
          schema:
            $ref: "#/definitions/ApiResponse"
  /logs:
    get:
      tags:
      - "log"
      summary: "Export logs"
      description: "Export logs for all servers"
      operationId: "exportLog"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Logs exported"
          schema:
            $ref: "#/definitions/Log"
        "403":
          description: "Forbidden from exporting logs"
          schema:
            $ref: "#/definitions/ApiResponse"
        "404":
          description: "Quota not found"
          schema:
            $ref: "#/definitions/ApiResponse"
        "405":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ApiResponse"
        "500":
          description: "TOC controller error"
          schema:
            $ref: "#/definitions/ApiResponse"
        "503":
          description: "Service unavailable"
          schema:
            $ref: "#/definitions/ApiResponse"
definitions:
  Severity:
    type: "string"
    enum:
    - "error"
    - "warning"
    - "info"
    - "debug"
    - "trace"
  Connections:
    type: "string"
    enum:
    - "online"
    - "offline"
  Statuses:
    type: "string"
    enum:
    - "queued"
    - "in-progress"
    - "completed"
    - "failed"
  Servers:
    type: "string"
    enum:
    - "web"
    - "file"
    - "db"
    - "mail"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
        description: "Severity level"
        enum:
        - "error"
        - "warning"
        - "info"
        - "debug"
        - "trace"
      message:
        type: "string"
    example:
      code: 0
      type: "type"
      message: "message"
  Snapshot:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      file:
        type: "string"
      status:
        type: "string"
        description: "Snapshot Status"
        enum:
        - "queued"
        - "in-progress"
        - "completed"
        - "failed"
      complete:
        type: "boolean"
    xml:
      name: "snapshot"
    example:
      file: "/var/opt/toc/archive/20241231T235959Z-server.tar.gz"
      id: 1
      status: "completed"
      complete: true
  Backup:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      time:
        type: "string"
        format: "date-time"
      snapshots:
        type: "array"
        items:
          $ref: "#/definitions/Snapshot"
    xml:
      name: "Backup"
    example:
      time: "20241231T235959Z"
      id: 1
  Restoration:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      backup:
        $ref: "#/definitions/Backup"
      status:
        type: "string"
        description: "Restoration Status"
        enum:
        - "queued"
        - "in-progress"
        - "completed"
        - "failed"
    xml:
      name: "Restoration"
    example:
      id: 1
  Transfer:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      backup:
        $ref: "#/definitions/Backup"
      status:
        type: "string"
        description: "Transfer Status"
        enum:
        - "queued"
        - "in-progress"
        - "completed"
        - "failed"
    xml:
      name: "Transfer"
    example:
      id: 1
      status: "failed"
  Synchronization:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      time:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Synchronization Status"
        enum:
        - "queued"
        - "in-progress"
        - "completed"
        - "failed"
      xml: {}
      example: {}
  Quota:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      path:
        type: "string"
      soft:
        type: "integer"
        format: "int64"
      hard:
        type: "integer"
        format: "int64"
      xml: {}
      example: {}
    example:
      path: "path"
      xml: ""
      id: 0
      hard: 1
      soft: 6
      example: ""
  Log:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      time:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Archive Status"
        enum:
        - "queued"
        - "in-progress"
        - "completed"
        - "failed"
      url:
        type: "string"
      xml: {}
      example: {}
    example:
      xml: ""
      id: 0
      time: "2000-01-23T04:56:07.000+00:00"
      url: "url"
      status: "queued"
      example: ""
  Archive:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      time:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Archive Status"
        enum:
        - "queued"
        - "in-progress"
        - "completed"
        - "failed"
      url:
        type: "string"
      xml: {}
      example: {}
externalDocs:
  description: "Find out more about TOC"
  url: "https://github.com/gyk4j/toc"
